# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RabbitMQPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RMQClient', '~> 0.10.0'
  
  # Pods for RabbitMQPractice

end
